src/Accelist.TC.WebDatabase/Entities/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Accelist.TC.WebDatabase.Entities
{
    public class Player
    {
        [Key]
        public string Email { get; set; }
        public string Password { get; set; }

    }
}

src/Accelist.TC.WebDatabase/Models/PlayerViewModel.cs
using Accelist.TC.WebDatabase.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Accelist.TC.WebDatabase.Models
{
    public class PlayerViewModel
    {
        public string Email { get; set; }
        public List<VideoGame> VideoGames { get; set; }
        public int TotalPage { get; set; }
    }
}

src/Accelist.TC.WebDatabase/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Accelist.TC.WebDatabase.Services;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Accelist.TC.WebDatabase.Controllers
{
    [Authorize(ActiveAuthenticationSchemes = "AccelistTrainingCenter")]
    public class PlayerController : Controller
    {
        public PlayerController(PlayerService playerService)
        {
            this.PlayerService = playerService;
        }

        private readonly PlayerService PlayerService;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var email = HttpContext.User.Claims.Where(Q => Q.Type == ClaimTypes.Email)
                .Select(Q => Q.Value).FirstOrDefault();
            var playerPage = await PlayerService.GetPlayerPage(email);
            return View(playerPage);
        }
        
        [Route("Player/GetPage/{pageNumber}")]
        public async Task<IActionResult> GetPage(int pageNumber)
        {
            var email = HttpContext.User.Claims.Where(Q => Q.Type == ClaimTypes.Email)
                .Select(Q => Q.Value).FirstOrDefault();
            return Ok(await PlayerService.GetPlayerPageByPageNumber(pageNumber, email));
        }
    }
}

src/Accelist.TC.WebDatabase/Controllers/VideoGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Accelist.TC.WebDatabase.Models;
using Accelist.TC.WebDatabase.Services;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Accelist.TC.WebDatabase.Controllers
{
    [Authorize(ActiveAuthenticationSchemes = "AccelistTrainingCenter")]
    [AutoValidateAntiforgeryToken]
    public class VideoGameController : Controller
    {
        public VideoGameController(VideoGameService videoGameService)
        {
            this.VideoGameService = videoGameService;
        }

        private readonly VideoGameService VideoGameService;

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateVideoGameViewModel createVideoGameViewModel)
        {
            if(ModelState.IsValid == false)
            {
                return RedirectToAction("Add");
            }
            var email = HttpContext.User.Claims.Where(Q => Q.Type == ClaimTypes.Email)
                .Select(Q => Q.Value).FirstOrDefault();
            await VideoGameService.AddNewVideoGame(createVideoGameViewModel, email);
            return RedirectToAction("Index", "Player");
        }


        public async Task<IActionResult> GetVideoGameImage(int id)
        {
            var videoGameImage = await VideoGameService.GetVideoGameImageByVideoGameId(id);
            return File(videoGameImage, "image/*");
        }
        
        [HttpDelete("{videoGameId}")]
        [Route("VideoGame/Delete/{videoGameId}")]
        public async Task<IActionResult> Delete(int videoGameId)
        {
            var email = HttpContext.User.Claims
                .Where(Q => Q.Type == ClaimTypes.Email)
                .Select(Q => Q.Value)
                .FirstOrDefault();
            await VideoGameService.DeleteVideoGame(videoGameId, email);
            return RedirectToAction("Index", "Player");
        }
        
        [Route("VideoGame/Edit/{videoGameId}")]
        public async Task<IActionResult> Edit(int videoGameId)
        {
            var videoGameDetail = await VideoGameService.GetVideoGameDetail(videoGameId);
            return View(videoGameDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditVideoGameViewModel editedVideoGame)
        {
            if(ModelState.IsValid == false)
            {
                return View();
            }
            await VideoGameService.UpdateVideoGame(editedVideoGame);
            return RedirectToAction("Index", "Player");
        }
    }
}

src/Accelist.TC.WebDatabase/Views/Player/Index.cshtml
@model Accelist.TC.WebDatabase.Models.PlayerViewModel

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1>
            Hi @Model.Email
            <a asp-action="Logout" asp-controller="Login" class="btn btn-link">Logout</a>
        </h1>
        <h2>
            Your game list:
        </h2>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Release Date</th>
                        <th>Cover</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody id="VideoGameList">
                    @{
                        var i = 1;
                        if (Model.VideoGames.Count == 0)
                        {
                            <tr>
                                <td colspan="7" class="text-center">
                                    Sorry, but you don't have any video game right now
                                </td>
                            </tr>
                        }
                        else
                        {
                            foreach (var game in Model.VideoGames)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@game.Name</td>
                                    <td>@game.Price</td>
                                    <td>@game.ReleaseDate.ToString("dd/MM/yyyy")</td>
                                    <td>
                                        <img src="@Url.Action("GetVideoGameImage", "VideoGame", new { id = game.VideoGameId })" />
                                    </td>
                                    <td>
                                        <a href="/VideoGame/Edit/@game.VideoGameId" class="btn btn-success">
                                            Edit
                                        </a>
                                    </td>
                                    <td>
                                        <a href="/VideoGame/Delete/@game.VideoGameId" class="btn btn-danger">
                                            Delete
                                        </a>
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <ul class="pagination">
            @{
                for (int j = 1; j <= Model.TotalPage; j++)
                {
                    <li>
                        <a href="#" id="page-btn-@j" page-number="@j">
                            @j
                        </a>
                    </li>
                }
            }
        </ul>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <a href="/VideoGame/Add" target="_blank" class="btn btn-default">
            Add Video Game
        </a>
    </div>
</div>